### ISSUE TITLE
make the project better

### ISSUE THREAD

**Issue by simranswaraj** [simranswaraj/Emotion-Recognition#1]

**Comment by swapnalshahil** [comment]
Please be specific about what you are saying!

**Comment by simranswaraj** [comment]
i want to make my project better with excellent accuracy.

**Comment by AbhiiGatty** [comment]
@simranswaraj Please create a README.md file explaining what your project is about, how to install and setup and be clear how  you want to improve the accuracy and where exactly you need help?

**Comment by simranswaraj** [comment]
Ya sure
